# Took some inspiration from https://github.com/inveniosoftware/invenio/blob/master/.travis.yml

sudo: required

# not using OS-level services since we want these in different containers
services:
  - docker

env:
  DOCKERFILE=Dockerfile.centos
  DOCKERFILE=Dockerfile.ubuntu
  CONTAINER='brucellino/invenio:test-ubuntu'
  CONTAINER="brucellino/invenio:test-centos"

cache:
  - apt
  - pip

before_install:
  - docker pull brucellino/invenio:test-ubuntu
  - docker pull brucellino/invenio:test-centos

script:
#  - docker build -f $DOCKERFILE .
  - docker run -t -v $PWD:/root/roles/invenio-docker-role $CONTAINER /bin/bash -c 'cp roles/invenio-docker-role/invenio.yml . ; ansible-playbook -c local invenio.yml'

notifications:
  slack: scigaia:byLKjoXfG8AKlsMgVK7q3Ooz
