# Took some inspiration from https://github.com/inveniosoftware/invenio/blob/master/.travis.yml

sudo: required

# not using OS-level services since we want these in different containers
services:
  - docker

env:
  DOCKERFILE=Dockerfile.centos
  DOCKERFILE=Dockerfile.ubuntu

cache:
  - apt
  - pip

before_install:
  - docker pull ubuntu:14.04.3
  - docker pull centos:6

script:
  - docker build -f $DOCKERFILE .

notifications:
  slack: scigaia:byLKjoXfG8AKlsMgVK7q3Ooz
