---
- name: Fix TTY
  hosts: localhost
  tasks:
    - name: Fix TTY
      replace:
        replace: "#Defaults requiretty"
        dest: /etc/sudoers
        regexp: '^Defaults requiretty'

- name: Invenio role
  hosts: localhost
  roles:
    - invenio-docker-role
