---
- name: Fix TTY
  hosts: localhost
  tasks:
    - name: Fix TTY
      replace:
        replace: "#Defaults requiretty"
        dest: /etc/sudoers
        regexp: '^Defaults requiretty'
- name: Temporary fix to crytpo
  hosts: localhost
  tasks:
    pip:
      name: cryptography
      state: absent

- name: Invenio role
  hosts: localhost
  roles:
    - invenio-docker-role
