---
- name: Fix TTY
  hosts: localhost
  tasks:
    - replace:
      replace: "#Defaults requiretty"
      dest: /etc/sudoers
      regexp: '^Defaults requiretty'

- name: Invenio role
  hosts: localhost
  roles:
    - invenio-docker-role
