---
# database setup
- name: install mysql client (Debian)
  sudo: true
  apt:
    name:  mysql-client
    state: present
  when: "ansible_os_family == 'Debian'"

- name: install mysql client (RedHat)
  sudo: true
  yum:
    name:  mysql-client
    state: present
  when: "ansible_os_family == 'RedHat'"
