# building invenio ... arg.
---

# This step is probably not idempotent.
- name: configure Invenio build
  command: "{{ item }}"
  args:
    chdir: "{{ invenio.build_dir }}/invenio-{{ invenio.version }}/"
  register: config
  with_items:
    - "{{ invenio.build_dir }}/invenio-{{ invenio.version }}/configure --prefix={{ invenio.install_dir }}"
    - make
    - make install

- name: Install Addons
  command: "make {{ item }}"
  args:
    chdir: "{{ invenio.build_dir}}/invenio-{{ invenio.version }}/"
  with_items: "{{ invenio.plugin_install }}"
  register: addons
