---
# pre-requisites.yml
- name: prerequisites debug
  debug:
    var: prerequisites['Debian']

- name: Install OS base pre-requisites (Debian)
  sudo: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ prerequisites.ansible_os_family }}"
  when: "ansible_os_family == 'Debian'"

- name: Install OS base pre-requisites (RedHat)
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ prerequisites.ansible_os_family }}"
  when: ansible_os_family  == 'RedHat'
