---
# pre-requisites.yml
- name: Install OS base pre-requisites (Debian)
  apt:
    name: {{ item }}
    state: present
  with_items: "{{ pre-requisites }}.{{ ansible_os_family }}"
  when: "{{ ansible_os_family }} == Debian"

- name: Install OS base pre-requisites (RedHat)
  yum:
    name: {{ item }}
    state: present
  with_items: "{{ pre-requisites.ansible_os_family }}"
  when: "{{ ansible_os_family }} == RedHat"
